### ISSUE TITLE
invalid_arg_name

### ISSUE THREAD

**Issue by tryllu** [steverobbins/Magento-Slack#2]
Hi,

I have encounter an error when posting through php script running externally.

Following is working when running from cli, as "php slack.php"

```
<?php
require_once 'app/Mage.php';

Mage::app();
$chat = Mage::getModel('slack/api_chat');
$chat->setChannel('baselinker');
$chat->setText('OK!')->postMessage();
```

However running same through "curl -X GET url_to_same_file_slack.php" give following error:

Debug:
```
    [body] => Array
        (
            [ok] =>
            [error] => invalid_arg_name
        )
```
Exception

```Fatal error</b>:  Uncaught exception 'Mage_Core_Exception' with message 'invalid_arg_name' in /public_html/app/Mage.php:595
Stack trace:
#0 /public_html/app/code/community/Steverobbins/Slack/Model/Api/Abstract.php(117): Mage::throwException('invalid_arg_nam...')
#1 /public_html/app/code/community/Steverobbins/Slack/Model/Api/Chat.php(37): Steverobbins_Slack_Model_Api_Abstract-&gt;__call('postMessage', Array)
#2 /public_html/app/code/community/Steverobbins/Slack/Model/Api/Chat.php(37): Steverobbins_Slack_Model_Api_Abstract-&gt;postMessage()
#3 /public_html/slack.php(7): Steverobbins_Slack_Model_Api_Chat-&gt;postMessage()
#4 {main}
  thrown in <b>/public_html/app/Mage.php</b> on line <b>595</b><br />
```

**Comment by steverobbins** [comment]
Not sure. Is your cli running the same version of PHP as your webserver?

Can you try logging/var_dump-ing `$name, $params` in `app/code/community/Steverobbins/Slack/Model/Api/Abstract.php:113`

**Comment by tryllu** [comment]
Yup. Tried with different php versions of cli. 

One more thing, I think it's somehow related to setopts encoding. Of course I will post additional logs.

Funny thing :) When you try to send two messages it also dumps an error. Even from cli.

```
<?php
require_once 'app/Mage.php';

Mage::app();
$chat = Mage::getModel('slack/api_chat');
$chat->setChannel('baselinker');
$chat->setText('OK1')->postMessage();
$chat->setText('OK2')->postMessage();
```

But the error is different:

> Uncaught Mage_Core_Exception: invalid_array_arg in /public_html/app/Mage.php:595

**Comment by tryllu** [comment]
```curl -X GET https://slack.php```
Log 1
```string(11) "postMessage"
array(4) {
  ["channel"]=>
  string(9) "hidden"
  ["text"]=>
  string(3) "OK1"
  ["username"]=>
  string(8) "auto_bot"
  ["token"]=>
  string(55) "hidden"
}
<br />
<b>Fatal error</b>:  Uncaught exception 'Mage_Core_Exception' with message 'invalid_arg_name' in /public_html/app/Mage.php:595
```

**Comment by tryllu** [comment]
Taken with
```
$params = $this->_prepareParams();
$result = $this->_post($name, $params);
var_dump($name);
var_dump($params);
```


```php56 slack.php```

```string(11) "postMessage"
array(4) {
  ["channel"]=>
  string(9) "hidden"
  ["text"]=>
  string(3) "OK1"
  ["username"]=>
  string(8) "auto_bot"
  ["token"]=>
  string(55) "hidden"
}
string(11) "postMessage"
array(5) {
  ["text"]=>
  string(3) "OK2"
  ["username"]=>
  string(8) "auto_bot"
  ["token"]=>
  string(55) "hidden"
  ["ts"]=>
  string(17) "1541457354.002800"
  ["message"]=>
  array(6) {
    ["text"]=>
    string(3) "OK1"
    ["username"]=>
    string(8) "auto_bot"
    ["bot_id"]=>
    string(9) "hidden"
    ["type"]=>
    string(7) "message"
    ["subtype"]=>
    string(11) "bot_message"
    ["ts"]=>
    string(17) "1541457354.002800"
  }
}
PHP Fatal error:  Uncaught exception 'Mage_Core_Exception' with message 'invalid_array_arg' in /public_html/app/Mage.php:595
Stack trace:
```
